django4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls"))
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name ="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags"),
    path("<int:post_id>/", post_detail, name = "post_detail"),
    path("<int:post_id>/like/", post_like, name = "post_like")
]

users/urls.py
from django.contrib import admin
from django.urls import path

from .views import login_view, logout_view, signup_view, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup_view, name = "signup"),
    path("<int:user_id>/profile/", profile, name = "profile"),
    path("<int:user_id>/followers/", followers, name = "followers"),
    path("<int:user_id>/following/", following, name = "following"),
    path("<int:user_id>/follow/", follow, name="follow")
]

posts/models.py
from django.db import models

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    content = models.TextField("내용")
    created = models.DateTimeField("작성일자", auto_now_add=True)
    
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)
    
    def __str__(self):
        return f"{self.user.username}의 Post(ID: {self.id})"
    
class PostImage(models.Model):
    post = models.ForeignKey(
        "Post",
        verbose_name="포스트",
        on_delete=models.CASCADE
    )
    photo = models.ImageField("사진", upload_to="post")
    
class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    post = models.ForeignKey(Post,verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일", auto_now_add=True)
    
class HashTag(models.Model):
    name = models.CharField("해시태그명", max_length=50)
    
    
    def __str__(self):
        return self.name

posts/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            # "user", # 이게 있게되면 유효성 검사시, Comment에서 user가 나오지 않기때문에 무조건 에러
            "post",
            "content",
        ]
        
        widget = {
            "content": forms.Textarea(
                attrs={"placeholder": "댓글 달기...",}
            )
        }
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

posts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

from .models import Post, Comment, PostImage, HashTag
from .forms import CommentForm, PostForm

# Create your views here.
def feeds(request):
    # 요청에 포함된 사용자가 로그인 하지 않은 경우
    if not request.user.is_authenticated:
        return redirect("users:login")
    
    # 모든 글 목록을 템플릿으로 전달
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts":posts,
        "comment_form": comment_form
        }
    return render(request, "posts/feeds.html", context)

@require_POST # 댓글 작성을 처리할 view, post 요청만 허용한다.
def comment_add(request):
    form = CommentForm(data = request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.save()
        
        # URL로 "next"값을 전달 받았다면, 댓글 작성 완료 후 전달 받은 값으로 이동한다.
        if request.GET.get("next"):
            url_next = request.GET.get("next")
        else:
            url_next = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url_next)
            
    
@require_POST
def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id = comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다.")
        
def post_add(request):
    if request.method == "POST":
        form = PostForm(data = request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            
            for image_file in request.FILES.getlist("images"):
                PostImage.objects.create(
                    post = post,
                    photo = image_file
                )
            
            # hashtag 라인
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_names = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name = tag_name)
                    post.tags.add(tag)
            
        
        url = reverse("posts:feeds") + f"#post-{post.id}"
        return HttpResponseRedirect(url)
    
    else:
        form = PostForm()
    context = {"form": form}
    return render(request, "posts/post_add.html", context)

def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name = tag_name)
    except HashTag.DoesNotExist:
        posts = Post.objects.none()
    else:
        posts = Post.objects.filter(tags = tag)
    
    context = {
        "posts": posts,
        "tag_name": tag_name
        }
    return render(request, "posts/tags.html", context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context= {
        "post": post,
        "comment_form":comment_form
              }
    return render(request, "posts/post_detail.html", context)

def post_like(request, post_id):
    post = Post.objects.get(id = post_id)
    user = request.user
    
    if user.like_posts.filter(id = post.id).exists():
        return user.like_posts.remove(post)
    else:
        user.like_posts.add(post)
        
    url = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url)

templates/posts/feeds.html
{% extends 'base_slider.html' %}
{% load custom_tags %}

{% block content %}
    <div id="feeds" class="post-container">
        {% for post in posts %}
            {% url 'posts:feeds' as action_redirect_to %}
            {% include "posts/post.html" with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
        {% endfor %}
    </div>
{% endblock content %}

templates/posts/post.html
<article class="post" id="post-{{post.id}}">
    <header class="post-header">
        <a href="{% url 'users:profile' user_id=user.id %}">
            {% if post.user.profile_image %}
                <img src="{{post.user.profile_image}}" alt="">
            {% endif %}
            <span>{{post.user.username}}</span>
        </a>

        <!--글의 작성자가 로그인한 사용자라면 팔로우 버튼을 표시하지 않는다.-->
        <!--자기 자신을 팔로우 하는 것을 방지-->
        {% if user != post.user %}
            <form action="{% url 'users:follow' user_id=user.id %}?next={{action_redirect_url}}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                    {% if post.user in user.following.all %}
                        Unfollow
                    {% else %}
                        Follow
                    {% endif %}
                </button>
            </form>
        {% endif %}
    </header>

    <!-- 이미지 슬라이드 영역 시작-->
    <div class="post-images splide">
        <div class="splide__track">
            <ul class="splide__list">
                {% if image.photo %}
                    <li class="splide_slide">
                        <img src="{{image.photo.url}}" alt="">
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!-- 이미지 슬라이드 영역 종료-->
    <div class="post-content">
        {{post.content|linebreaksbr}}
        <div class="post-tags">
            {% for tag in post.tags.all %}
                <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>

    <div class="post-buttons">
        <form action="{% url 'posts:post_like' post_id=post.id %}?next={{action_redirect_url}}" method="post">
            {% csrf_token %}
            <button type="submit">
                {% if user in post.like_users.all %}
                    style="color:red,;"
                {% endif %}
                Likes({{post.like_users.count}})
            </button>
        </form>
        <!-- 댓글 갯수 표현-->
        <span>Comments ({{post.comment_set.count}})</span>
    </div>

    <div class="post-comments">
        <ul>
            {% for comment in post.comment_set.all %}
            <li>
                <span>{{comment.user.username}}</span>
                <span>{{comment.content}}</span>

                <!--댓글 삭제-->
                {% if user == comment.user %}
                    <form action="{% url 'posts:comment_delete' comment_id=comment.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">삭제</button>
                    </form>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>

    <small>{{post.created}}</small>
    <div class="post-comment-create">
        <form action="{% url 'posts:comment_add' %}?next={{action_redirect_url}}" method="post">
            {% csrf_token %}
            <input type="hidden" name="post" value="{{post.id}}">
            {{comment_form.content}}
            <button type="submit">게시</button>
        </form>
        
    </div>
</article>

templates/posts/post_add.html
{% extends 'base_nav.html' %}
{% block content %}
<div id="post-add">
    <h1>post add</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_images">이미지</label>
            <input type="file" id="id_images" name="images" multiple>
        </div>
        {{form.as_p}}
        <div>
            <label for="id_tags">해시태그</label>
            <input name="tags" type="text" id="id_tags" placeholder="구분은 (,)쉼표로 하기">
        </div>
        <button type="submit">게시</button>
    </form>
</div>
{% endblock content %}

templates/posts/post_detail.html
{% extends 'base_slider.html' %}

{% block content %}
    <div id="feeds" class="post-container">
        {% url 'posts:feeds' post.id as action_redirect_to %}
        {% include "posts/post.html" with action_redirect_url=action_redirect_to %}
    </div>
{% endblock content %}

templates/posts/tags.html
{% extends 'base_nav.html' %}
{% block content %}
<div id="tags">
    <header class="tags-header">
        <h2>#{{tag_name}}</h2>
        <div>게시물{{posts.count}}</div>
    </header>
    <div class="post-grid-container">
        {% for post in posts %}
            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <a href="{% url 'posts:post_detail' post_id=post.id %}">
                        <img src="{{post.postimage_set.first.photo.url}}" alt="">    
                    </a>
                </div>
            {% endif %}
            {%empty%}
                <p>검색된 게시물이 없습니다.</p>
        {% endfor %}
    </div>
</div>
{% endblock content %}