django4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls"))
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name ="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags"),
    path("<int:post_id>/", post_detail, name = "post_detail"),
    path("<int:post_id>/like/", post_like, name = "post_like")
]

users/urls.py
from django.contrib import admin
from django.urls import path

from .views import login_view, logout_view, signup_view, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup_view, name = "signup"),
    path("<int:user_id>/profile/", profile, name = "profile"),
    path("<int:user_id>/followers/", followers, name = "followers"),
    path("<int:user_id>/following/", following, name = "following"),
    path("<int:user_id>/follow/", follow, name="follow")
]

posts/models.py
from django.db import models

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    content = models.TextField("내용")
    created = models.DateTimeField("작성일자", auto_now_add=True)
    
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)
    
    def __str__(self):
        return f"{self.user.username}의 Post(ID: {self.id})"
    
class PostImage(models.Model):
    post = models.ForeignKey(
        "Post",
        verbose_name="포스트",
        on_delete=models.CASCADE
    )
    photo = models.ImageField("사진", upload_to="post")
    
class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    post = models.ForeignKey(Post,verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일", auto_now_add=True)
    
class HashTag(models.Model):
    name = models.CharField("해시태그명", max_length=50)
    
    
    def __str__(self):
        return self.name

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}
    {% endblock head %}
</head>
<body>
    {% block base_content %}
    {% endblock base_content %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
    <script src="{% static 'splide/splide.js' %}"></script>
</head>
<body>
    {% include "nav.html" %}
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include "nav.html" %}
    {% block content %}
    {% endblock content %}
{% endblock base_content %}

templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        {% if user.profile_image %}
            <img src="{{user.profile_image.url}}" alt="">
        {% endif %}
    

        <div class="info-texts">
            <h1>{{user.username}}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts</dt>
                    <dd>
                        <a href="{% url 'users:profile' user_id=user.id %}">
                            {{user.post_set.count}}
                        </a>
                    </dd>
                    <dt>Followers</dt>
                    <dd>
                        <a href="{% url 'users:followers' user_id=user.id %}">
                            {{user.followers.count}}
                        </a>
                    </dd>
                    <dt>Following</dt>
                    <dd>
                        <a href="{% url 'users:following' user_id=user.id %}">
                            {{user.following.count}}
                        </a>
                    </dd>
                </dl>
            </div>
            <p>{{user.short_description}}</p>
        </div>
    </div>
    {% block bottom_data %}
    {% endblock bottom_data %}
</div>
{% endblock content %}

templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock head %}

{% block base_content %}
    {% include "nav.html" %}
    {% block content %}
    {% endblock content %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.lenth; i++){
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock base_content %}

templates/nav.html
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Noabo</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">포스트추가</a>
    <a href="{% url 'users:logout' %}">로그아웃</a>
</nav>