django4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls"))
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name ="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags"),
    path("<int:post_id>/", post_detail, name = "post_detail"),
    path("<int:post_id>/like/", post_like, name = "post_like")
]

users/urls.py
from django.contrib import admin
from django.urls import path

from .views import login_view, logout_view, signup_view, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup_view, name = "signup"),
    path("<int:user_id>/profile/", profile, name = "profile"),
    path("<int:user_id>/followers/", followers, name = "followers"),
    path("<int:user_id>/following/", following, name = "following"),
    path("<int:user_id>/follow/", follow, name="follow")
]

posts/models.py
from django.db import models

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    content = models.TextField("내용")
    created = models.DateTimeField("작성일자", auto_now_add=True)
    
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)
    
    def __str__(self):
        return f"{self.user.username}의 Post(ID: {self.id})"
    
class PostImage(models.Model):
    post = models.ForeignKey(
        "Post",
        verbose_name="포스트",
        on_delete=models.CASCADE
    )
    photo = models.ImageField("사진", upload_to="post")
    
class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    post = models.ForeignKey(Post,verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일", auto_now_add=True)
    
class HashTag(models.Model):
    name = models.CharField("해시태그명", max_length=50)
    
    
    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Relationship(models.Model):
    from_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우 요청한 유저",
        related_name="following_relationships",
        on_delete=models.CASCADE
    )
    to_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우 요청의 대상",
        related_name="follower_relationships",
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"관계 ({self.from_user} -> ({self.to_user}))"
    
class User(AbstractUser):
    profile_image = models.ImageField(
        "프로필 이미지", upload_to="users/profile", blank=True
    )
    short_description = models.TextField(
        "소개글", blank=True
    )
    
    # 좋아요 기능
    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name="내가 좋아요 누른 Post 목록",
        related_name="like_users", # 이건 역참조로 들어가서 posts폴더에 있는 Post 모델에 붙여주는 역할을 한다.
        blank=True
    )
    
    following = models.ManyToManyField(
        "self",
        verbose_name="팔로우 중인 유저들",
        related_name="followers",
        symmetrical=False,
        through = "users.Relationship"
    )
    
    def __str__(self):
        return self.username
    

users/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget = forms.TextInput(
            attrs = {"placeholder": "아이디 입력해주세요 (3자리 이상)"},
        ),
        )
    password = forms.CharField(
        min_length=4,
        widget = forms.PasswordInput(
            attrs = {"placeholder": "비밀번호 입력해주세요 (4자리 이상)"},
        ),
        )
    
class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget = forms.PasswordInput)
    password2 = forms.CharField(widget = forms.PasswordInput)
    profile_image = forms.ImageField()
    short_description = forms.CharField()
    
    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username = username).exists():
            raise ValidationError(f"{username}아이디는 이미 존재 합니다.")
        return username
        
    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            self.add_error("password2", "비밀번호 입력값 다름")
            
    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data['password1']
        profile_image = self.cleaned_data["profile_image"]
        short_description = self.cleaned_data["short_description"]
        user = User.objects.create_user(
            username = username,
            password = password1,
            profile_image = profile_image,
            short_description = short_description
        )
        return user

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import User
from .forms import LoginForm, SignupForm

# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect("posts:feeds")
    
    if request.method == "POST":
        form = LoginForm(data = request.POST)
        
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            
            user = authenticate(username = username, password = password)
        
            if user:
                login(request, user)
                return redirect("posts:feeds")
            
            else:
                form.add_error(None, "에러입니다.")
        
        context = {"form": form}
        return render(request, "users/login.html", context)
            
    
    else:
        form = LoginForm()
        context= {"form": form}
        return render(request, "users/login.html", context)
    
def logout_view(request):
    logout(request)
    return redirect("users:login")

def signup_view(request):
    if request.method == "POST":
        form = SignupForm(data = request.POST, files = request.FILES)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("posts:feeds")
        else:
            context = {"form":form}
                
    else:
        form = SignupForm()
        
    context = {"form": form}
    return render(request, "users/signup.html", context)

def profile(request, user_id):
    user = get_object_or_404(User, id = user_id)
    context = {
        "user":user
    }
    return render(request, "users/profile.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id = user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user": user,
        "relationships": relationships
    }
    return render(request, "users/followers.html", context)

def following(request, user_id):
    user = get_object_or_404(User, id = user_id)
    relationships = user.following_relationships.all()
    context = {
        "user":user,
        "relationships":relationships
    }
    return render(request, "users/following.html", context)

def follow(request, user_id):
    # 로그인한 유저
    
    user = request.user
    #팔로우 하려는 유저
    
    target_user = get_object_or_404(User, id=user_id)
    #팔로우하려는 유저가 이미 자신의 팔로잉 목록에 있는 경우
    
    if target_user in user.following.all():
        user.following.remove(target_user)
    #팔로우 하려는 유저가 자신의 팔로우 목록에 없는 경우
    else:
        user.following.add(target_user)
    #팔로우 토글 후 이동할 URL이 전달되엇다면 해당 주소로
    url_next = request.GET.get("next") or reverse("users:profile" ,args=[user.id])
    return HttpResponseRedirect(url_next)

templates/users/followers.html
{% extends "base_profile.html" %}

{% block bottom_data %}
<div class="relationships">
    <h3>Followers</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
                {% if relationship.from_user.profile_image %}
                    <img src="{{relationship.from_user.profile_image.url}}" alt="">
                {% endif %}
                <div class="relationship-info">
                    <span>{{relationship.from_user.username}}</span>
                    <span>{{relationship.created|date:"y.m.d"}}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock bottom_data %}

templates/users/following.html
{% extends "base_profile.html" %}

{% block bottom_data %}
<div class="relationships">
    <h3>Following</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.to_user.id %}">
                {% if relationship.to_user.profile_image %}
                    <img src="{{relationship.to_user.profile_image.url}}" alt="">
                {% endif %}
                <div class="relationship-info">
                    <span>{{relationship.to_user.username}}</span>
                    <span>{{relationship.created|date:"y.m.d"}}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock bottom_data %}

templates/users/login.html
{% extends "base.html" %}
{% block content %}
<div id="login">
    <form action="" method="post">
        <h1>login</h1>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-login">제출</button>
        <a href="{% url 'users:signup' %}">회원가입 페이지로 이동</a>
    </form>
</div>
{% endblock content %}

templates/users/profile.html
{% extends 'base_profile.html' %}

{% block bottom_data %}
    <div class="post-grid-container">
        {% for post in user.post_set.all %}
            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <a href="{% url 'posts:post_detail' post_id=post.id %}">
                        <img src="{{post.postimage_set.first.photo.url}}" alt="">
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock bottom_data %}

templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
<div id="signup">
    <form action="" method="post" enctype="multipart/form-data">
        <h1>signup</h1>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-signup">회원가입</button>
        <a href="{% url 'users:login' %}">로그인페이지로 이동</a>
    </form>
</div>
{% endblock content %}